package com.commoncoder.calendar.ai.agent.enums;

public enum QueryType {
  CHECK_AVAILABILITY,
  EVENT_CREATION,
  EVENT_UPDATE,
  EVENT_SUMMARIZATION,
  EVENT_ACL_CHANGE,
  CALENDAR_CREATION,
  CALENDAR_LIST_UPDATE,
  CALENDAR_METADATA_UPDATE,
  CALENDAR_ACL_CHANGE,
  UNKNOWN
}
